version: '3'

services:  # play with docker config
  jupyter:
    container_name: web
    image: liuderchi/jupyter-nodejs
    ports:
      - "8888"
    volumes:
      - sharedVolume:/root/learn-js-in-jupyter
  notebooks:
    image: liuderchi/learn-js-in-jupyter
    volumes:
      - sharedVolume:/home/learn-js-in-jupyter
volumes:
  sharedVolume: {}
